application:
    appName: sti
    email:
        endereco-remetente: jhordan.orto@gmail.com
        nome-remetente: Jhordan

spring:
    application:
        name: service
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/sti
        username: sti
        password: sti
    jackson:
        date-format: yyyy-MM-dd
        deserialization:
            fail-on-unknown-properties: false
    jpa:
#        database-platform: io.github.jhipster.domain.util.FixedPostgreSQL95Dialect
        database: POSTGRESQL
        show-sql: true
        open-in-view: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: false
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    liquibase:
        change-log: classpath:/config/liquibase/master.xml
        drop-first: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: jhordan.orto@gmail.com
        password: Barro2424
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    quitwait: false
server:
    port: 8080